### ISSUE TITLE
cant load worlds

### ISSUE THREAD

**Issue by spike11302000** [Codepixl/GLCraft#13]
java.io.FileNotFoundException: ~/GLCraft/saves/test/player.nbt (No such file or directory)
	at java.io.FileInputStream.open0(Native Method)
	at java.io.FileInputStream.open(FileInputStream.java:195)
	at java.io.FileInputStream.<init>(FileInputStream.java:138)
	at java.io.FileInputStream.<init>(FileInputStream.java:93)
	at net.codepixl.GLCraft.util.data.saves.SaveManager.loadWorld(SaveManager.java:155)
	at net.codepixl.GLCraft.world.WorldManager.loadWorld(WorldManager.java:546)
	at net.codepixl.GLCraft.GUI.GUISinglePlayer$2.call(GUISinglePlayer.java:70)
	at net.codepixl.GLCraft.GUI.GUISinglePlayer$2.call(GUISinglePlayer.java:1)
	at net.codepixl.GLCraft.GUI.Elements.GUIButton.invokeClick(GUIButton.java:183)
	at net.codepixl.GLCraft.GUI.GUISinglePlayer.loadSave(GUISinglePlayer.java:167)
	at net.codepixl.GLCraft.GUI.GUISave.input(GUISave.java:67)
	at net.codepixl.GLCraft.GUI.Elements.GUIScrollBox.input(GUIScrollBox.java:145)
	at net.codepixl.GLCraft.GUI.GUIScreen.input(GUIScreen.java:102)
	at net.codepixl.GLCraft.GUI.GUIManager.input(GUIManager.java:140)
	at net.codepixl.GLCraft.world.CentralManager.input(CentralManager.java:178)
	at net.codepixl.GLCraft.world.CentralManager.update(CentralManager.java:514)
	at net.codepixl.GLCraft.GLCraft.update(GLCraft.java:245)
	at net.codepixl.GLCraft.GLCraft.commonInitializer(GLCraft.java:137)
	at net.codepixl.GLCraft.GLCraft.<init>(GLCraft.java:110)
	at net.codepixl.GLCraft.GLCraft.main(GLCraft.java:284)

**Comment by Codepixl** [comment]
Your world seems to have been corrupted for some reason, because the player.nbt file doesn't exist. Try generating a world in the latest commit, I fixed some of those issues and made world saving faster with a new format (you can load old worlds too, it will upgrade them)

**Comment by spike11302000** [comment]
i made a new world and i still could not load it

**Comment by spike11302000** [comment]
oh.. you need to create the save folder at "~/GLCraft/saves' for linux/mac

**Comment by Codepixl** [comment]
That's... weird. so you're saying that that folder wasn't there before, even though it was listing the saves?

**Comment by spike11302000** [comment]
i think i just fixed it

**Comment by spike11302000** [comment]
it made a folder called "~" in glcraft source code and the game got confused where files are

**Comment by Codepixl** [comment]
Oh, okay.

**Comment by spike11302000** [comment]
i just pushed the commit it should be fixed

**Comment by spike11302000** [comment]
water is really laggy

**Comment by spike11302000** [comment]
ok world loading is fixed

**Comment by Codepixl** [comment]
Alright cool, and yeah I know it is I'm gonna fix that sometime

**Comment by spike11302000** [comment]
im going to work with adding stuff to bluestone. like bluestone torches

**Comment by Codepixl** [comment]
Okay, I'm working on lighting so try not to mess around with the Chunk class

**Comment by spike11302000** [comment]
i wont

**Comment by spike11302000** [comment]
is there i way i can cheat in items?

**Comment by Codepixl** [comment]
You can edit the save with NbtExplorer, but otherwise no

**Comment by spike11302000** [comment]
ok

**Comment by spike11302000** [comment]
i love it when non linux program works on linux XD

**Comment by spike11302000** [comment]
well kida work...
