### ISSUE TITLE
loading world crashes game

### ISSUE THREAD

**Issue by spike11302000** [Codepixl/GLCraft#15]
java.lang.NullPointerException
	at net.codepixl.GLCraft.world.WorldManager.evalLight(WorldManager.java:752)
	at net.codepixl.GLCraft.world.WorldManager.relight(WorldManager.java:666)
	at net.codepixl.GLCraft.world.Chunk.update(Chunk.java:351)
	at net.codepixl.GLCraft.world.WorldManager.update(WorldManager.java:184)
	at net.codepixl.GLCraft.world.CentralManager.update(CentralManager.java:513)
	at net.codepixl.GLCraft.GLCraft.update(GLCraft.java:245)
	at net.codepixl.GLCraft.GLCraft.commonInitializer(GLCraft.java:137)
	at net.codepixl.GLCraft.GLCraft.<init>(GLCraft.java:110)
	at net.codepixl.GLCraft.GLCraft.main(GLCraft.java:284)

**Comment by Codepixl** [comment]
I think I know how to fix this. It shouldn't happen, though. Are you on the latest commit? (Let there be (sun) light)

**Comment by spike11302000** [comment]
yes

**Comment by Codepixl** [comment]
Alright, I think I fixed it. I just have some other bugs to fix too though

**Comment by spike11302000** [comment]
ok

**Comment by spike11302000** [comment]
its fixed
