### ISSUE TITLE
dedicated stop ticking after breaking blocks

### ISSUE THREAD

**Issue by spike11302000** [Codepixl/GLCraft#17]
Uncaught exception thrown in thread main
java.util.ConcurrentModificationException
        at java.util.ArrayList$Itr.checkForComodification(ArrayList.java:901)
        at java.util.ArrayList$Itr.next(ArrayList.java:851)
        at net.codepixl.GLCraft.world.entity.EntityManager.update(EntityManager.java:164)
        at net.codepixl.GLCraft.world.WorldManager.update(WorldManager.java:240)
        at net.codepixl.GLCraft.world.CentralManager.update(CentralManager.java:664)
        at net.codepixl.GLCraft.GLCraft.update(GLCraft.java:386)
        at net.codepixl.GLCraft.GLCraft.commonInitializer(GLCraft.java:240)
        at net.codepixl.GLCraft.GLCraft.<init>(GLCraft.java:122)
        at net.codepixl.GLCraft.GLCraft.main(GLCraft.java:415)

Exception: java.awt.HeadlessException thrown from the UncaughtExceptionHandler in thread "main"

**Comment by Codepixl** [comment]
This has now been fixed.
