### ISSUE TITLE
Compilaing Error

### ISSUE THREAD

**Issue by francolongo** [Codepixl/GLCraft#31]
Uncaught exception thrown in thread main
java.lang.NullPointerException
	at net.codepixl.GLCraft.GLCraft.loadIcon(GLCraft.java:410)
	at net.codepixl.GLCraft.GLCraft.commonInitializer(GLCraft.java:142)
	at net.codepixl.GLCraft.GLCraft.<init>(GLCraft.java:90)
	at net.codepixl.GLCraft.GLCraft.main(GLCraft.java:395)

Exception: java.lang.NullPointerException thrown from the UncaughtExceptionHandler in thread "main"

**Comment by francolongo** [comment]
yes

**Comment by francolongo** [comment]
hello

**Comment by Codepixl** [comment]
You said "yes", that doesn't help me. Which one are you running it from? Are you running it from the source code in an IDE and compiling it yourself? Or did you download the JAR file from the website? What operating system are you on?
