### ISSUE TITLE
Can't join world for 2nt time.

### ISSUE THREAD

**Issue by IsaiahPatton** [Codepixl/GLCraft#34]
1. Create a world and join world
2. Save & Exit the game
3. Relaunch game
4. Try to join world
5. Fails to join world

```
java.lang.NullPointerException
	at net.codepixl.GLCraft.world.WorldManager.loadChunks(WorldManager.java:535)
	at net.codepixl.GLCraft.util.data.saves.SaveManager.loadWorld(SaveManager.java:108)
	at net.codepixl.GLCraft.world.WorldManager.loadWorld(WorldManager.java:785)
	at net.codepixl.GLCraft.GUI.GUISinglePlayer$2.call(GUISinglePlayer.java:69)
	at net.codepixl.GLCraft.GUI.GUISinglePlayer$2.call(GUISinglePlayer.java:1)
	at net.codepixl.GLCraft.GUI.Elements.GUIButton.input(GUIButton.java:134)
	at net.codepixl.GLCraft.GUI.GUIScreen.input(GUIScreen.java:110)
	at net.codepixl.GLCraft.GUI.GUIManager.input(GUIManager.java:129)
	at net.codepixl.GLCraft.world.CentralManager.input(CentralManager.java:195)
	at net.codepixl.GLCraft.world.CentralManager.update(CentralManager.java:659)
	at net.codepixl.GLCraft.GLCraft.update(GLCraft.java:368)
	at net.codepixl.GLCraft.GLCraft.commonInitializer(GLCraft.java:157)
	at net.codepixl.GLCraft.GLCraft.<init>(GLCraft.java:90)
	at net.codepixl.GLCraft.GLCraft.main(GLCraft.java:395)
[SERVER] Error loading world

```

**Comment by Codepixl** [comment]
I'm not really working on GLCraft anymore. Feel free to fork it and work on it if you want though!
